#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import annotations
from typing import TYPE_CHECKING
import tcod.event

from core_components.events.base import BaseGameEvent
if TYPE_CHECKING:
    from state import GameState
    from core_components.entities.library import BaseEntity, Charactor, AICharactor


"""This module contains all event classes used by the game to respond to various situations. An Input Event is a wrapper to trigger actions from player input events from tcod (keyboard/mouse)."""
"""Base class for all game events."""
class SystemEvent(BaseGameEvent):
    message: str
    def __init__(self, message: str = "System Event Triggered") -> None:
        self.message = message


class InputEvent(BaseGameEvent):
    event: tcod.event.Event
    message: str

    def __init__(self, event: tcod.event.Event, message: str = "TCOD Event", ) -> None:
        self.message = message
        self.event = event


class EntityEvent(BaseGameEvent):
    entity: BaseEntity | None
    message: str

    def __init__(self, 
                 entity: BaseEntity | None = None, 
                 message: str = "Entity Event Triggered") -> None:
        if entity:
            self.entity = entity
        self.message = message


class CharactorEvent(BaseGameEvent):
    entity: Charactor | None
    target: Charactor | None
    state: GameState | None
    message: str

    def __init__(self, 
                 entity: Charactor | None = None,
                 target: Charactor | None = None,
                 state: GameState | None = None, 
                 message: str = "Charactor Event Triggered") -> None:
        self.message=message
        if entity:
            self.entity = entity
        if target:
            self.target = target
        if state:
            self.state = state


class AIEvent(BaseGameEvent):
    entity: AICharactor | None
    target: Charactor | None
    state: GameState | None
    message: str

    def __init__(self, 
                 entity: AICharactor | None = None, 
                 target: Charactor | None = None, 
                 state: GameState | None = None,  
                 message: str = "AI Event Triggered") -> None:
        
        self.message=message
        if entity:
            self.entity = entity
        if target:
            self.target = target
        if state:
            self.state = state


"""These System Events are generated by the game engine itself. They are not tied to any specific entity or AI, but rather represent global game states or actions."""
class GameStartEvent(SystemEvent):
    def __init__(self, message: str = "Game Start") -> None:
        super().__init__(message)


class GameOverEvent(SystemEvent):
    pass


class FOVUpdateEvent(SystemEvent):
    def __init__(self, message: str) -> None:
        super().__init__(message)
    """Triggers the FOV update for all entities."""


"""These Entity Events are generated by entities in response to actions or interactions."""
class NoCollision(EntityEvent):
    def __init__(self, entity: BaseEntity, message: str) -> None:
        super().__init__(entity, message)


class WallCollision(EntityEvent):
    def __init__(self, entity: BaseEntity, message: str) -> None:
        super().__init__(entity, message)


class MapBoundaryCollision(EntityEvent):
    def __init__(self, entity: BaseEntity, message: str) -> None:
        super().__init__(entity, message)


class TargetCollision(EntityEvent):
    def __init__(self, entity: BaseEntity, message: str) -> None:
        super().__init__(entity, message)
    

class MeleeCollision(EntityEvent):
    def __init__(self, entity: BaseEntity, message: str) -> None:
        super().__init__(entity, message)


"""These Combat Events are generated during combat interactions between entities and require targeting information."""
class EntityCombatEvent(CharactorEvent):
    def __init__(self, entity: Charactor | None = None, target: Charactor | None = None) -> None:
        super().__init__(entity=entity, target=target)
        self.target: Charactor | None = target


class MeleeAttackEvent(EntityCombatEvent):
    entity: Charactor | None
    target: Charactor | None

    def __init__(self, entity: Charactor | None = None, target: Charactor | None = None) -> None:
        self.entity = entity
        self.target = target


class MissileAttackEvent(EntityCombatEvent):
    pass


class SpellAttackEvent(EntityCombatEvent):
    pass


"""These AI Events are generated by AI-controlled entities to trigger AI generated behaviors."""
class TargetedAIEvent(AIEvent):
    def __init__(self, entity: AICharactor, target: Charactor) -> None:
        self.entity = entity
        self.target = target


class AttackedAIEvent(AIEvent):
    def __init__(self, entity: AICharactor, target: Charactor) -> None:
        self.entity = entity
        self.target = target


class TargetAvailableAIEvent(AIEvent):
    entity: AICharactor | None
    target: Charactor | None
    
    def __init__(self, entity: AICharactor | None = None, target: Charactor | None = None) -> None:
            self.entity = entity
            self.target = target


class OnTargetAIEvent(AIEvent):
    def __init__(self, entity: AICharactor | None = None, target: Charactor | None = None) -> None:
        if entity:
            self.entity = entity
        if target:
            self.target = target


class TargetOutOfRangeAIEvent(AIEvent):
    entity: AICharactor | None
    target: Charactor | None
    
    def __init__(self, entity: AICharactor | None = None, target: Charactor | None = None) -> None:
            self.entity = entity
            self.target = target