from __future__ import annotations
from typing import TYPE_CHECKING

import tcod

from core_components.entities.library import BaseEntity, Charactor, AICharactor

if TYPE_CHECKING:
    from core_components.store import GameStore
    from core_components.loops.handlers import GameLoopHandler


class BaseEvent:
    state: GameStore | None
    transformer: object | None

    def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None) -> None:
        self.state = state
        self.transformer = handler
    
    def trigger(self) -> None:
        self.transformer.dispatch(self) # type: ignore


class NonEvent(BaseEvent):
    def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None) -> None:
        super().__init__(handler, state)


class SystemEvent(BaseEvent):
    def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None) -> None:
        super().__init__(handler, state)


class InputEvent(BaseEvent):
    event: tcod.event.Event

    def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, event: tcod.event.Event | None = None) -> None:
        super().__init__(handler, state)

        if event:
            self.event = event


class EntityEvent(BaseEvent):
    entity: BaseEntity | None

    def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: BaseEntity | None = None) -> None:
        super().__init__(handler, state)

        if entity:
            self.entity = entity


class CharactorEvent(BaseEvent):
    entity: Charactor | None
    target: Charactor | None

    def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: Charactor | None = None, target: Charactor | None = None) -> None:
        super().__init__(handler, state)

        if entity:
            self.entity = entity
        if target:
            self.target = target
        if state:
            self.state = state


class AIEvent(BaseEvent):
    entity: AICharactor | None
    target: Charactor | None

    def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: AICharactor | None = None, target: Charactor | None = None) -> None:
        super().__init__(handler, state)

        if entity:
            self.entity = entity
        if target:
            self.target = target
        if state:
            self.state = state


"""These System Events are generated by the game engine itself. They are not tied to any specific entity or AI, but rather represent global game states or actions."""
class GameStartEvent(SystemEvent):
    def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None) -> None:
        super().__init__(handler, state)


class GameOverEvent(SystemEvent):
    def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None) -> None:
        super().__init__(handler, state)


class FOVUpdateEvent(SystemEvent):
    def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None) -> None:
        super().__init__(handler, state)
    """Triggers the FOV update for all entities."""


"""These Entity Events are generated by entities in response to actions or interactions."""
class NoCollision(EntityEvent):
    def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: BaseEntity | None = None) -> None:
        super().__init__(handler, state, entity=entity)


class WallCollision(EntityEvent):
    def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: BaseEntity | None = None) -> None:
        super().__init__(handler, state, entity=entity)


class MapBoundaryCollision(EntityEvent):
    def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: BaseEntity | None = None) -> None:
        super().__init__(handler, state, entity=entity)


class TargetCollision(EntityEvent):
    def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: BaseEntity | None = None) -> None:
        super().__init__(handler, state, entity=entity)
    

class MeleeCollision(EntityEvent):
    def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: BaseEntity | None = None) -> None:
        super().__init__(handler, state, entity=entity)


"""These Combat Events are generated during combat interactions between entities and require targeting information."""
class EntityCombatEvent(CharactorEvent):
    def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: Charactor | None = None, target: Charactor | None = None) -> None:
        super().__init__(handler, state, entity=entity, target=target)


class MeleeAttackEvent(EntityCombatEvent):
    entity: Charactor | None
    target: Charactor | None

    def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: Charactor | None = None, target: Charactor | None = None) -> None:
        super().__init__(handler, state, entity=entity, target=target)


class MissileAttackEvent(EntityCombatEvent):
    pass


class SpellAttackEvent(EntityCombatEvent):
    pass


"""These AI Events are generated by AI-controlled entities to trigger AI generated behaviors."""
class TargetedAIEvent(AIEvent):
    def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: AICharactor | None = None, target: Charactor | None = None) -> None:
        super().__init__(handler, state, entity=entity, target=target)


class AttackedAIEvent(AIEvent):
    def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: AICharactor | None = None, target: Charactor | None = None) -> None:
        super().__init__(handler, state, entity=entity, target=target)


class TargetAvailableAIEvent(AIEvent):
    def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: AICharactor | None = None, target: Charactor | None = None) -> None:
        super().__init__(handler, state, entity=entity, target=target)


class OnTargetAIEvent(AIEvent):
    def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: AICharactor | None = None, target: Charactor | None = None) -> None:
        super().__init__(handler, state, entity=entity, target=target)


class TargetOutOfRangeAIEvent(AIEvent):
    def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: AICharactor | None = None, target: Charactor | None = None) -> None:
        super().__init__(handler, state, entity=entity, target=target)