#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import annotations

###
# A BEHAVIOR is the pair of an EVENT and an ACTION that together define a discrete unit of functionality for an entity.
# The EVENT encapsulates the occurrence that triggers an ACTION, while the ACTION defines the specific operations.
# An EVENT can only be linked to one ACTION, but an ACTION can be triggered by multiple EVENTS.
# This design allows for modular and reusable behavior definitions that can be easily managed within the game loop
# architecture.
###

###
# An EVENT should follow this pattern:
# CALLED BY: An entity or system when a specific condition occurs that requires handling.
# 1. Encapsulate all relevant information about the occurrence that needs to be passed to the associated ACTION in the behavior.
# 2. Implement a trigger method that, when called, sends the EVENT to the appropriate loop handler for processing.
###

####
# An ACTION should follow this pattern:
# CALLED BY: An EVENT that is created by an entity or system OR directly called by another ACTION to form a chained sequence of ACTIONS.
# 1. Check pre-conditions (e.g., is the entity able to perform the action? At least the action_locked check should be done here)
# 2. Perform the action's main logic.
#    - Typically involves running through the entity's state machine to determine outcomes based on current state and action parameters.
#    - Should NOT directly trigger state updates. These triggers should be handled by the enity's state machine as a result of the action's effects.
# 3. Handle post-action effects (e.g. trigger follow-up events, log outcomes).
#    - Chained ACTIONS have two options:
#       a) Directly call the next ACTION in the sequence. This creates a synchronous flow between actions.
#       b) Create and an EVENT or ACTION and send it to the loop handler. This allows for asynchronous and flexible action sequences.
####

# """These System Events are generated by the game engine itself. They are not tied to any specific entity or AI, but rather represent global game states or actions."""
# class GameStartEvent(SystemEvent):
#     pass




# class GameOverEvent(SystemEvent):
#     def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None) -> None:
#         super().__init__(handler, state)


# class FOVUpdateEvent(SystemEvent):
#     def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None) -> None:
#         super().__init__(handler, state)
#     """Triggers the FOV update for all entity_components"""


# """These Entity Events are generated by entities in response to actions or interactions."""
# class NoCollision(EntityEvent):
#     def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: BaseGameEntity | None = None) -> None:
#         super().__init__(handler, state, entity=entity)


# class WallCollision(EntityEvent):
#     def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: BaseGameEntity | None = None) -> None:
#         super().__init__(handler, state, entity=entity)


# class MapBoundaryCollision(EntityEvent):
#     def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: BaseGameEntity | None = None) -> None:
#         super().__init__(handler, state, entity=entity)


# class TargetCollision(EntityEvent):
#     def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: BaseGameEntity | None = None) -> None:
#         super().__init__(handler, state, entity=entity)
    

# class MeleeCollision(EntityEvent):
#     def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: BaseGameEntity | None = None) -> None:
#         super().__init__(handler, state, entity=entity)


# """These Combat Events are generated during combat interactions between entities and require targeting information."""
# class EntityCombatEvent(PlayerCharacterEvent):
#     def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: Character | None = None, target: Character | None = None) -> None:
#         super().__init__(handler, state, entity=entity, target=target)


# class MeleeAttackEvent(EntityCombatEvent):
#     entity: Character | None
#     target: Character | None

#     def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: Character | None = None, target: Character | None = None) -> None:
#         super().__init__(handler, state, entity=entity, target=target)


# class MissileAttackEvent(EntityCombatEvent):
#     pass


# class SpellAttackEvent(EntityCombatEvent):
#     pass


# """These AI Events are generated by AI-controlled entities to trigger AI generated behaviors."""
# class TargetedAIEvent(AICharacterEvent):
#     def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: AICharacter | None = None, target: Character | None = None) -> None:
#         super().__init__(handler, state, entity=entity, target=target)


# class AttackedAIEvent(AICharacterEvent):
#     def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: AICharacter | None = None, target: Character | None = None) -> None:
#         super().__init__(handler, state, entity=entity, target=target)


# class TargetAvailableAIEvent(AICharacterEvent):
#     def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: AICharacter | None = None, target: Character | None = None) -> None:
#         super().__init__(handler, state, entity=entity, target=target)


# class OnTargetAIEvent(AICharacterEvent):
#     def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: AICharacter | None = None, target: Character | None = None) -> None:
#         super().__init__(handler, state, entity=entity, target=target)


# class TargetOutOfRangeAIEvent(AICharacterEvent):
    # def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: AICharacter | None = None, target: Character | None = None) -> None:
    #     super().__init__(handler, state, entity=entity, target=target)