#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import annotations



# """These System Events are generated by the game engine itself. They are not tied to any specific entity or AI, but rather represent global game states or actions."""
# class GameStartEvent(SystemEvent):
#     pass




# class GameOverEvent(SystemEvent):
#     def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None) -> None:
#         super().__init__(handler, state)


# class FOVUpdateEvent(SystemEvent):
#     def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None) -> None:
#         super().__init__(handler, state)
#     """Triggers the FOV update for all entities."""


# """These Entity Events are generated by entities in response to actions or interactions."""
# class NoCollision(EntityEvent):
#     def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: BaseGameEntity | None = None) -> None:
#         super().__init__(handler, state, entity=entity)


# class WallCollision(EntityEvent):
#     def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: BaseGameEntity | None = None) -> None:
#         super().__init__(handler, state, entity=entity)


# class MapBoundaryCollision(EntityEvent):
#     def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: BaseGameEntity | None = None) -> None:
#         super().__init__(handler, state, entity=entity)


# class TargetCollision(EntityEvent):
#     def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: BaseGameEntity | None = None) -> None:
#         super().__init__(handler, state, entity=entity)
    

# class MeleeCollision(EntityEvent):
#     def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: BaseGameEntity | None = None) -> None:
#         super().__init__(handler, state, entity=entity)


# """These Combat Events are generated during combat interactions between entities and require targeting information."""
# class EntityCombatEvent(PlayerCharacterEvent):
#     def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: Character | None = None, target: Character | None = None) -> None:
#         super().__init__(handler, state, entity=entity, target=target)


# class MeleeAttackEvent(EntityCombatEvent):
#     entity: Character | None
#     target: Character | None

#     def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: Character | None = None, target: Character | None = None) -> None:
#         super().__init__(handler, state, entity=entity, target=target)


# class MissileAttackEvent(EntityCombatEvent):
#     pass


# class SpellAttackEvent(EntityCombatEvent):
#     pass


# """These AI Events are generated by AI-controlled entities to trigger AI generated behaviors."""
# class TargetedAIEvent(AICharacterEvent):
#     def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: AICharacter | None = None, target: Character | None = None) -> None:
#         super().__init__(handler, state, entity=entity, target=target)


# class AttackedAIEvent(AICharacterEvent):
#     def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: AICharacter | None = None, target: Character | None = None) -> None:
#         super().__init__(handler, state, entity=entity, target=target)


# class TargetAvailableAIEvent(AICharacterEvent):
#     def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: AICharacter | None = None, target: Character | None = None) -> None:
#         super().__init__(handler, state, entity=entity, target=target)


# class OnTargetAIEvent(AICharacterEvent):
#     def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: AICharacter | None = None, target: Character | None = None) -> None:
#         super().__init__(handler, state, entity=entity, target=target)


# class TargetOutOfRangeAIEvent(AICharacterEvent):
    # def __init__(self, handler: GameLoopHandler | None = None, state: GameStore | None = None, entity: AICharacter | None = None, target: Character | None = None) -> None:
    #     super().__init__(handler, state, entity=entity, target=target)